# Generated by Django 5.1.1 on 2024-10-01 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='coment',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='created_at',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='privacity',
            new_name='privacidade',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categoria',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='receitas.category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredientes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mododepreparo',
            field=models.TextField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tempodepreparo',
            field=models.TimeField(blank=True),
        ),
    ]
