# Generated by Django 5.1.1 on 2024-10-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_rename_category_category_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.category'),
        ),
    ]
